// Generated by CoffeeScript 1.3.3
(function() {

  require(['app/MotoMap', 'app/authMachine'], function(MotoMap, authMachine) {
    return $(function() {
      var checkAuth, identity, loginButton, logoutButton, motoMap;
      motoMap = new MotoMap("map");
      $('#download').click(function() {
        return motoMap.download();
      });
      loginButton = $('#loginButton');
      logoutButton = $('#logoutButton');
      identity = $('#identity');
      loginButton.click(authMachine.login);
      logoutButton.click(authMachine.logout);
      checkAuth = function() {
        if (authMachine.identity != null) {
          loginButton.hide();
          logoutButton.show();
          return identity.text(authMachine.identity);
        } else {
          loginButton.show();
          logoutButton.hide();
          return identity.text('');
        }
      };
      authMachine.onLoginSuccess = checkAuth;
      authMachine.onLogoutSuccess = checkAuth;
      return checkAuth();
    });
  });

}).call(this);
